// Theme configurations for Baby Name Swiper
const themes = {
    generic: {
        id: 'generic',
        name: '✨ Classic',
        description: 'Timeless favorites',
        colors: {
            primary: '#667eea',
            secondary: '#764ba2',
            cardName: '#667eea',
            boyBg: '#e3f2fd',
            boyText: '#1976d2',
            girlBg: '#fce4ec',
            girlText: '#c2185b'
        },
        icons: {
            like: '❤️',
            pass: '❌',
            boy: '👦',
            girl: '👧'
        },
        names: [
            // Boy names (25)
            { name: "Liam", gender: "boy" },
            { name: "Noah", gender: "boy" },
            { name: "Oliver", gender: "boy" },
            { name: "Elijah", gender: "boy" },
            { name: "James", gender: "boy" },
            { name: "William", gender: "boy" },
            { name: "Benjamin", gender: "boy" },
            { name: "Lucas", gender: "boy" },
            { name: "Henry", gender: "boy" },
            { name: "Theodore", gender: "boy" },
            { name: "Jack", gender: "boy" },
            { name: "Levi", gender: "boy" },
            { name: "Alexander", gender: "boy" },
            { name: "Jackson", gender: "boy" },
            { name: "Mateo", gender: "boy" },
            { name: "Daniel", gender: "boy" },
            { name: "Michael", gender: "boy" },
            { name: "Mason", gender: "boy" },
            { name: "Sebastian", gender: "boy" },
            { name: "Ethan", gender: "boy" },
            { name: "Logan", gender: "boy" },
            { name: "Owen", gender: "boy" },
            { name: "Samuel", gender: "boy" },
            { name: "Jacob", gender: "boy" },
            { name: "Asher", gender: "boy" },
            
            // Girl names (25)
            { name: "Olivia", gender: "girl" },
            { name: "Emma", gender: "girl" },
            { name: "Charlotte", gender: "girl" },
            { name: "Amelia", gender: "girl" },
            { name: "Ava", gender: "girl" },
            { name: "Sophia", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Mia", gender: "girl" },
            { name: "Evelyn", gender: "girl" },
            { name: "Harper", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Camila", gender: "girl" },
            { name: "Gianna", gender: "girl" },
            { name: "Elizabeth", gender: "girl" },
            { name: "Eleanor", gender: "girl" },
            { name: "Ella", gender: "girl" },
            { name: "Abigail", gender: "girl" },
            { name: "Sofia", gender: "girl" },
            { name: "Avery", gender: "girl" },
            { name: "Scarlett", gender: "girl" },
            { name: "Emily", gender: "girl" },
            { name: "Aria", gender: "girl" },
            { name: "Penelope", gender: "girl" },
            { name: "Chloe", gender: "girl" },
            { name: "Layla", gender: "girl" }
        ]
    },
    
    fantasy: {
        id: 'fantasy',
        name: '🧙 Fantasy',
        description: 'Magical and enchanted',
        colors: {
            primary: '#9333ea',
            secondary: '#c026d3',
            cardName: '#9333ea',
            boyBg: '#f3e8ff',
            boyText: '#7c3aed',
            girlBg: '#fae8ff',
            girlText: '#c026d3'
        },
        icons: {
            like: '⭐',
            pass: '🌙',
            boy: '🧙',
            girl: '🧚'
        },
        names: [
            // Boy names (25)
            { name: "Merlin", gender: "boy" },
            { name: "Arthur", gender: "boy" },
            { name: "Gandalf", gender: "boy" },
            { name: "Orion", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Atlas", gender: "boy" },
            { name: "Draco", gender: "boy" },
            { name: "Evander", gender: "boy" },
            { name: "Caspian", gender: "boy" },
            { name: "Griffin", gender: "boy" },
            { name: "Perseus", gender: "boy" },
            { name: "Sage", gender: "boy" },
            { name: "Rowan", gender: "boy" },
            { name: "Jasper", gender: "boy" },
            { name: "Finnian", gender: "boy" },
            { name: "Arlo", gender: "boy" },
            { name: "Sirius", gender: "boy" },
            { name: "Felix", gender: "boy" },
            { name: "Oren", gender: "boy" },
            { name: "Magnus", gender: "boy" },
            { name: "Alaric", gender: "boy" },
            { name: "Lucian", gender: "boy" },
            { name: "Theron", gender: "boy" },
            { name: "Zephyr", gender: "boy" },
            { name: "Cedric", gender: "boy" },
            
            // Girl names (25)
            { name: "Luna", gender: "girl" },
            { name: "Aurora", gender: "girl" },
            { name: "Celeste", gender: "girl" },
            { name: "Freya", gender: "girl" },
            { name: "Seraphina", gender: "girl" },
            { name: "Elara", gender: "girl" },
            { name: "Lyra", gender: "girl" },
            { name: "Arwen", gender: "girl" },
            { name: "Galadriel", gender: "girl" },
            { name: "Astrid", gender: "girl" },
            { name: "Iris", gender: "girl" },
            { name: "Ophelia", gender: "girl" },
            { name: "Calliope", gender: "girl" },
            { name: "Persephone", gender: "girl" },
            { name: "Athena", gender: "girl" },
            { name: "Selene", gender: "girl" },
            { name: "Nova", gender: "girl" },
            { name: "Aria", gender: "girl" },
            { name: "Elora", gender: "girl" },
            { name: "Isla", gender: "girl" },
            { name: "Avalon", gender: "girl" },
            { name: "Melody", gender: "girl" },
            { name: "Willow", gender: "girl" },
            { name: "Faye", gender: "girl" },
            { name: "Elvira", gender: "girl" }
        ]
    },
    
    nature: {
        id: 'nature',
        name: '🌿 Nature',
        description: 'Earth and garden inspired',
        colors: {
            primary: '#059669',
            secondary: '#0d9488',
            cardName: '#047857',
            boyBg: '#d1fae5',
            boyText: '#065f46',
            girlBg: '#ccfbf1',
            girlText: '#0f766e'
        },
        icons: {
            like: '🌸',
            pass: '🍂',
            boy: '🌲',
            girl: '🌺'
        },
        names: [
            // Boy names (25)
            { name: "Forrest", gender: "boy" },
            { name: "River", gender: "boy" },
            { name: "Sage", gender: "boy" },
            { name: "Aspen", gender: "boy" },
            { name: "Cedar", gender: "boy" },
            { name: "Oakley", gender: "boy" },
            { name: "Reed", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Jasper", gender: "boy" },
            { name: "Rowan", gender: "boy" },
            { name: "Brooks", gender: "boy" },
            { name: "Forest", gender: "boy" },
            { name: "Cliff", gender: "boy" },
            { name: "Stone", gender: "boy" },
            { name: "Heath", gender: "boy" },
            { name: "Glen", gender: "boy" },
            { name: "Sterling", gender: "boy" },
            { name: "Ridge", gender: "boy" },
            { name: "Dale", gender: "boy" },
            { name: "Clay", gender: "boy" },
            { name: "Wolf", gender: "boy" },
            { name: "Hawk", gender: "boy" },
            { name: "Hunter", gender: "boy" },
            { name: "Bear", gender: "boy" },
            { name: "Flint", gender: "boy" },
            
            // Girl names (25)
            { name: "Willow", gender: "girl" },
            { name: "Ivy", gender: "girl" },
            { name: "Rose", gender: "girl" },
            { name: "Lily", gender: "girl" },
            { name: "Violet", gender: "girl" },
            { name: "Hazel", gender: "girl" },
            { name: "Jade", gender: "girl" },
            { name: "Iris", gender: "girl" },
            { name: "Flora", gender: "girl" },
            { name: "Fern", gender: "girl" },
            { name: "Daisy", gender: "girl" },
            { name: "Poppy", gender: "girl" },
            { name: "Magnolia", gender: "girl" },
            { name: "Autumn", gender: "girl" },
            { name: "Summer", gender: "girl" },
            { name: "Sky", gender: "girl" },
            { name: "Ocean", gender: "girl" },
            { name: "Coral", gender: "girl" },
            { name: "Pearl", gender: "girl" },
            { name: "Rain", gender: "girl" },
            { name: "Meadow", gender: "girl" },
            { name: "Briar", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Aurora", gender: "girl" },
            { name: "Celeste", gender: "girl" }
        ]
    },
    
    royal: {
        id: 'royal',
        name: '👑 Royal',
        description: 'Regal and elegant',
        colors: {
            primary: '#7c2d12',
            secondary: '#991b1b',
            cardName: '#7c2d12',
            boyBg: '#fef3c7',
            boyText: '#92400e',
            girlBg: '#fce7f3',
            girlText: '#9f1239'
        },
        icons: {
            like: '👑',
            pass: '🗡️',
            boy: '🤴',
            girl: '👸'
        },
        names: [
            // Boy names (25)
            { name: "Alexander", gender: "boy" },
            { name: "William", gender: "boy" },
            { name: "Henry", gender: "boy" },
            { name: "Charles", gender: "boy" },
            { name: "Edward", gender: "boy" },
            { name: "George", gender: "boy" },
            { name: "Louis", gender: "boy" },
            { name: "Frederick", gender: "boy" },
            { name: "Arthur", gender: "boy" },
            { name: "Philip", gender: "boy" },
            { name: "Leopold", gender: "boy" },
            { name: "Augustus", gender: "boy" },
            { name: "Sebastian", gender: "boy" },
            { name: "Maximilian", gender: "boy" },
            { name: "Theodore", gender: "boy" },
            { name: "Nicholas", gender: "boy" },
            { name: "Edmund", gender: "boy" },
            { name: "Vincent", gender: "boy" },
            { name: "Benedict", gender: "boy" },
            { name: "Reginald", gender: "boy" },
            { name: "Constantine", gender: "boy" },
            { name: "Ferdinand", gender: "boy" },
            { name: "Xavier", gender: "boy" },
            { name: "Octavian", gender: "boy" },
            { name: "Basil", gender: "boy" },
            
            // Girl names (25)
            { name: "Elizabeth", gender: "girl" },
            { name: "Victoria", gender: "girl" },
            { name: "Catherine", gender: "girl" },
            { name: "Margaret", gender: "girl" },
            { name: "Alexandra", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Charlotte", gender: "girl" },
            { name: "Eleanor", gender: "girl" },
            { name: "Beatrice", gender: "girl" },
            { name: "Arabella", gender: "girl" },
            { name: "Genevieve", gender: "girl" },
            { name: "Cordelia", gender: "girl" },
            { name: "Josephine", gender: "girl" },
            { name: "Theodora", gender: "girl" },
            { name: "Anastasia", gender: "girl" },
            { name: "Vivienne", gender: "girl" },
            { name: "Penelope", gender: "girl" },
            { name: "Rosalind", gender: "girl" },
            { name: "Seraphina", gender: "girl" },
            { name: "Evangeline", gender: "girl" },
            { name: "Adelaide", gender: "girl" },
            { name: "Matilda", gender: "girl" },
            { name: "Philippa", gender: "girl" },
            { name: "Henrietta", gender: "girl" },
            { name: "Clementine", gender: "girl" }
        ]
    },
    
    modern: {
        id: 'modern',
        name: '⚡ Modern',
        description: 'Trendy and fresh',
        colors: {
            primary: '#0891b2',
            secondary: '#0284c7',
            cardName: '#0e7490',
            boyBg: '#cffafe',
            boyText: '#155e75',
            girlBg: '#fce7f3',
            girlText: '#9f1239'
        },
        icons: {
            like: '💯',
            pass: '👎',
            boy: '🚀',
            girl: '💎'
        },
        names: [
            // Boy names (25)
            { name: "Aiden", gender: "boy" },
            { name: "Jayden", gender: "boy" },
            { name: "Kayden", gender: "boy" },
            { name: "Brayden", gender: "boy" },
            { name: "Grayson", gender: "boy" },
            { name: "Mason", gender: "boy" },
            { name: "Carter", gender: "boy" },
            { name: "Parker", gender: "boy" },
            { name: "Jaxon", gender: "boy" },
            { name: "Maverick", gender: "boy" },
            { name: "Axel", gender: "boy" },
            { name: "Knox", gender: "boy" },
            { name: "Ryker", gender: "boy" },
            { name: "Zane", gender: "boy" },
            { name: "Cash", gender: "boy" },
            { name: "Ace", gender: "boy" },
            { name: "King", gender: "boy" },
            { name: "Legend", gender: "boy" },
            { name: "Titan", gender: "boy" },
            { name: "Atlas", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Crew", gender: "boy" },
            { name: "Blaze", gender: "boy" },
            { name: "Dash", gender: "boy" },
            { name: "Cruz", gender: "boy" },
            
            // Girl names (25)
            { name: "Aria", gender: "girl" },
            { name: "Nova", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Paisley", gender: "girl" },
            { name: "Kinsley", gender: "girl" },
            { name: "Brooklyn", gender: "girl" },
            { name: "Harper", gender: "girl" },
            { name: "Riley", gender: "girl" },
            { name: "Skylar", gender: "girl" },
            { name: "Addison", gender: "girl" },
            { name: "Peyton", gender: "girl" },
            { name: "Quinn", gender: "girl" },
            { name: "Sloane", gender: "girl" },
            { name: "Juniper", gender: "girl" },
            { name: "Ember", gender: "girl" },
            { name: "Wren", gender: "girl" },
            { name: "Ivy", gender: "girl" },
            { name: "Hadley", gender: "girl" },
            { name: "Brielle", gender: "girl" },
            { name: "Melody", gender: "girl" },
            { name: "Dakota", gender: "girl" },
            { name: "Sienna", gender: "girl" },
            { name: "Kaia", gender: "girl" },
            { name: "Presley", gender: "girl" },
            { name: "Reign", gender: "girl" }
        ]
    }
};
