// Theme configurations for Baby Name Swiper
const themes = {
    generic: {
        id: 'generic',
        name: '✨ Classic',
        description: 'Timeless favorites',
        colors: {
            primary: '#667eea',
            secondary: '#764ba2',
            cardName: '#667eea',
            boyBg: '#e3f2fd',
            boyText: '#1976d2',
            girlBg: '#fce4ec',
            girlText: '#c2185b'
        },
        icons: {
            like: '❤️',
            pass: '❌',
            boy: '👦',
            girl: '👧'
        },
        names: [
            // Boy names (25)
            { name: "Liam", gender: "boy" },
            { name: "Noah", gender: "boy" },
            { name: "Oliver", gender: "boy" },
            { name: "Elijah", gender: "boy" },
            { name: "James", gender: "boy" },
            { name: "William", gender: "boy" },
            { name: "Benjamin", gender: "boy" },
            { name: "Lucas", gender: "boy" },
            { name: "Henry", gender: "boy" },
            { name: "Theodore", gender: "boy" },
            { name: "Jack", gender: "boy" },
            { name: "Levi", gender: "boy" },
            { name: "Alexander", gender: "boy" },
            { name: "Jackson", gender: "boy" },
            { name: "Mateo", gender: "boy" },
            { name: "Daniel", gender: "boy" },
            { name: "Michael", gender: "boy" },
            { name: "Mason", gender: "boy" },
            { name: "Sebastian", gender: "boy" },
            { name: "Ethan", gender: "boy" },
            { name: "Logan", gender: "boy" },
            { name: "Owen", gender: "boy" },
            { name: "Samuel", gender: "boy" },
            { name: "Jacob", gender: "boy" },
            { name: "Asher", gender: "boy" },
            
            // Girl names (25)
            { name: "Olivia", gender: "girl" },
            { name: "Emma", gender: "girl" },
            { name: "Charlotte", gender: "girl" },
            { name: "Amelia", gender: "girl" },
            { name: "Ava", gender: "girl" },
            { name: "Sophia", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Mia", gender: "girl" },
            { name: "Evelyn", gender: "girl" },
            { name: "Harper", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Camila", gender: "girl" },
            { name: "Gianna", gender: "girl" },
            { name: "Elizabeth", gender: "girl" },
            { name: "Eleanor", gender: "girl" },
            { name: "Ella", gender: "girl" },
            { name: "Abigail", gender: "girl" },
            { name: "Sofia", gender: "girl" },
            { name: "Avery", gender: "girl" },
            { name: "Scarlett", gender: "girl" },
            { name: "Emily", gender: "girl" },
            { name: "Aria", gender: "girl" },
            { name: "Penelope", gender: "girl" },
            { name: "Chloe", gender: "girl" },
            { name: "Layla", gender: "girl" }
        ]
    },
    
    fantasy: {
        id: 'fantasy',
        name: '🧙 Fantasy',
        description: 'Magical and enchanted',
        colors: {
            primary: '#9333ea',
            secondary: '#c026d3',
            cardName: '#9333ea',
            boyBg: '#f3e8ff',
            boyText: '#7c3aed',
            girlBg: '#fae8ff',
            girlText: '#c026d3'
        },
        icons: {
            like: '⭐',
            pass: '🌙',
            boy: '🧙',
            girl: '🧚'
        },
        names: [
            // Boy names (25)
            { name: "Merlin", gender: "boy" },
            { name: "Arthur", gender: "boy" },
            { name: "Gandalf", gender: "boy" },
            { name: "Orion", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Atlas", gender: "boy" },
            { name: "Draco", gender: "boy" },
            { name: "Evander", gender: "boy" },
            { name: "Caspian", gender: "boy" },
            { name: "Griffin", gender: "boy" },
            { name: "Perseus", gender: "boy" },
            { name: "Sage", gender: "boy" },
            { name: "Rowan", gender: "boy" },
            { name: "Jasper", gender: "boy" },
            { name: "Finnian", gender: "boy" },
            { name: "Arlo", gender: "boy" },
            { name: "Sirius", gender: "boy" },
            { name: "Felix", gender: "boy" },
            { name: "Oren", gender: "boy" },
            { name: "Magnus", gender: "boy" },
            { name: "Alaric", gender: "boy" },
            { name: "Lucian", gender: "boy" },
            { name: "Theron", gender: "boy" },
            { name: "Zephyr", gender: "boy" },
            { name: "Cedric", gender: "boy" },
            
            // Girl names (25)
            { name: "Luna", gender: "girl" },
            { name: "Aurora", gender: "girl" },
            { name: "Celeste", gender: "girl" },
            { name: "Freya", gender: "girl" },
            { name: "Seraphina", gender: "girl" },
            { name: "Elara", gender: "girl" },
            { name: "Lyra", gender: "girl" },
            { name: "Arwen", gender: "girl" },
            { name: "Galadriel", gender: "girl" },
            { name: "Astrid", gender: "girl" },
            { name: "Iris", gender: "girl" },
            { name: "Ophelia", gender: "girl" },
            { name: "Calliope", gender: "girl" },
            { name: "Persephone", gender: "girl" },
            { name: "Athena", gender: "girl" },
            { name: "Selene", gender: "girl" },
            { name: "Nova", gender: "girl" },
            { name: "Aria", gender: "girl" },
            { name: "Elora", gender: "girl" },
            { name: "Isla", gender: "girl" },
            { name: "Avalon", gender: "girl" },
            { name: "Melody", gender: "girl" },
            { name: "Willow", gender: "girl" },
            { name: "Faye", gender: "girl" },
            { name: "Elvira", gender: "girl" }
        ]
    },
    
    nature: {
        id: 'nature',
        name: '🌿 Nature',
        description: 'Earth and garden inspired',
        colors: {
            primary: '#059669',
            secondary: '#0d9488',
            cardName: '#047857',
            boyBg: '#d1fae5',
            boyText: '#065f46',
            girlBg: '#ccfbf1',
            girlText: '#0f766e'
        },
        icons: {
            like: '🌸',
            pass: '🍂',
            boy: '🌲',
            girl: '🌺'
        },
        names: [
            // Boy names (25)
            { name: "Forrest", gender: "boy" },
            { name: "River", gender: "boy" },
            { name: "Sage", gender: "boy" },
            { name: "Aspen", gender: "boy" },
            { name: "Cedar", gender: "boy" },
            { name: "Oakley", gender: "boy" },
            { name: "Reed", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Jasper", gender: "boy" },
            { name: "Rowan", gender: "boy" },
            { name: "Brooks", gender: "boy" },
            { name: "Forest", gender: "boy" },
            { name: "Cliff", gender: "boy" },
            { name: "Stone", gender: "boy" },
            { name: "Heath", gender: "boy" },
            { name: "Glen", gender: "boy" },
            { name: "Sterling", gender: "boy" },
            { name: "Ridge", gender: "boy" },
            { name: "Dale", gender: "boy" },
            { name: "Clay", gender: "boy" },
            { name: "Wolf", gender: "boy" },
            { name: "Hawk", gender: "boy" },
            { name: "Hunter", gender: "boy" },
            { name: "Bear", gender: "boy" },
            { name: "Flint", gender: "boy" },
            
            // Girl names (25)
            { name: "Willow", gender: "girl" },
            { name: "Ivy", gender: "girl" },
            { name: "Rose", gender: "girl" },
            { name: "Lily", gender: "girl" },
            { name: "Violet", gender: "girl" },
            { name: "Hazel", gender: "girl" },
            { name: "Jade", gender: "girl" },
            { name: "Iris", gender: "girl" },
            { name: "Flora", gender: "girl" },
            { name: "Fern", gender: "girl" },
            { name: "Daisy", gender: "girl" },
            { name: "Poppy", gender: "girl" },
            { name: "Magnolia", gender: "girl" },
            { name: "Autumn", gender: "girl" },
            { name: "Summer", gender: "girl" },
            { name: "Sky", gender: "girl" },
            { name: "Ocean", gender: "girl" },
            { name: "Coral", gender: "girl" },
            { name: "Pearl", gender: "girl" },
            { name: "Rain", gender: "girl" },
            { name: "Meadow", gender: "girl" },
            { name: "Briar", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Aurora", gender: "girl" },
            { name: "Celeste", gender: "girl" }
        ]
    },
    
    royal: {
        id: 'royal',
        name: '👑 Royal',
        description: 'Regal and elegant',
        colors: {
            primary: '#7c2d12',
            secondary: '#991b1b',
            cardName: '#7c2d12',
            boyBg: '#fef3c7',
            boyText: '#92400e',
            girlBg: '#fce7f3',
            girlText: '#9f1239'
        },
        icons: {
            like: '👑',
            pass: '🗡️',
            boy: '🤴',
            girl: '👸'
        },
        names: [
            // Boy names (25)
            { name: "Alexander", gender: "boy" },
            { name: "William", gender: "boy" },
            { name: "Henry", gender: "boy" },
            { name: "Charles", gender: "boy" },
            { name: "Edward", gender: "boy" },
            { name: "George", gender: "boy" },
            { name: "Louis", gender: "boy" },
            { name: "Frederick", gender: "boy" },
            { name: "Arthur", gender: "boy" },
            { name: "Philip", gender: "boy" },
            { name: "Leopold", gender: "boy" },
            { name: "Augustus", gender: "boy" },
            { name: "Sebastian", gender: "boy" },
            { name: "Maximilian", gender: "boy" },
            { name: "Theodore", gender: "boy" },
            { name: "Nicholas", gender: "boy" },
            { name: "Edmund", gender: "boy" },
            { name: "Vincent", gender: "boy" },
            { name: "Benedict", gender: "boy" },
            { name: "Reginald", gender: "boy" },
            { name: "Constantine", gender: "boy" },
            { name: "Ferdinand", gender: "boy" },
            { name: "Xavier", gender: "boy" },
            { name: "Octavian", gender: "boy" },
            { name: "Basil", gender: "boy" },
            
            // Girl names (25)
            { name: "Elizabeth", gender: "girl" },
            { name: "Victoria", gender: "girl" },
            { name: "Catherine", gender: "girl" },
            { name: "Margaret", gender: "girl" },
            { name: "Alexandra", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Charlotte", gender: "girl" },
            { name: "Eleanor", gender: "girl" },
            { name: "Beatrice", gender: "girl" },
            { name: "Arabella", gender: "girl" },
            { name: "Genevieve", gender: "girl" },
            { name: "Cordelia", gender: "girl" },
            { name: "Josephine", gender: "girl" },
            { name: "Theodora", gender: "girl" },
            { name: "Anastasia", gender: "girl" },
            { name: "Vivienne", gender: "girl" },
            { name: "Penelope", gender: "girl" },
            { name: "Rosalind", gender: "girl" },
            { name: "Seraphina", gender: "girl" },
            { name: "Evangeline", gender: "girl" },
            { name: "Adelaide", gender: "girl" },
            { name: "Matilda", gender: "girl" },
            { name: "Philippa", gender: "girl" },
            { name: "Henrietta", gender: "girl" },
            { name: "Clementine", gender: "girl" }
        ]
    },
    
    modern: {
        id: 'modern',
        name: '⚡ Modern',
        description: 'Trendy and fresh',
        colors: {
            primary: '#0891b2',
            secondary: '#0284c7',
            cardName: '#0e7490',
            boyBg: '#cffafe',
            boyText: '#155e75',
            girlBg: '#fce7f3',
            girlText: '#9f1239'
        },
        icons: {
            like: '💯',
            pass: '👎',
            boy: '🚀',
            girl: '💎'
        },
        names: [
            // Boy names (25)
            { name: "Aiden", gender: "boy" },
            { name: "Jayden", gender: "boy" },
            { name: "Kayden", gender: "boy" },
            { name: "Brayden", gender: "boy" },
            { name: "Grayson", gender: "boy" },
            { name: "Mason", gender: "boy" },
            { name: "Carter", gender: "boy" },
            { name: "Parker", gender: "boy" },
            { name: "Jaxon", gender: "boy" },
            { name: "Maverick", gender: "boy" },
            { name: "Axel", gender: "boy" },
            { name: "Knox", gender: "boy" },
            { name: "Ryker", gender: "boy" },
            { name: "Zane", gender: "boy" },
            { name: "Cash", gender: "boy" },
            { name: "Ace", gender: "boy" },
            { name: "King", gender: "boy" },
            { name: "Legend", gender: "boy" },
            { name: "Titan", gender: "boy" },
            { name: "Atlas", gender: "boy" },
            { name: "Phoenix", gender: "boy" },
            { name: "Crew", gender: "boy" },
            { name: "Blaze", gender: "boy" },
            { name: "Dash", gender: "boy" },
            { name: "Cruz", gender: "boy" },
            
            // Girl names (25)
            { name: "Aria", gender: "girl" },
            { name: "Nova", gender: "girl" },
            { name: "Luna", gender: "girl" },
            { name: "Paisley", gender: "girl" },
            { name: "Kinsley", gender: "girl" },
            { name: "Brooklyn", gender: "girl" },
            { name: "Harper", gender: "girl" },
            { name: "Riley", gender: "girl" },
            { name: "Skylar", gender: "girl" },
            { name: "Addison", gender: "girl" },
            { name: "Peyton", gender: "girl" },
            { name: "Quinn", gender: "girl" },
            { name: "Sloane", gender: "girl" },
            { name: "Juniper", gender: "girl" },
            { name: "Ember", gender: "girl" },
            { name: "Wren", gender: "girl" },
            { name: "Ivy", gender: "girl" },
            { name: "Hadley", gender: "girl" },
            { name: "Brielle", gender: "girl" },
            { name: "Melody", gender: "girl" },
            { name: "Dakota", gender: "girl" },
            { name: "Sienna", gender: "girl" },
            { name: "Kaia", gender: "girl" },
            { name: "Presley", gender: "girl" },
            { name: "Reign", gender: "girl" }
        ]
    },
    
    irish: {
        id: 'irish',
        name: '☘️ Irish',
        description: 'Celtic heritage names',
        colors: {
            primary: '#16a34a',
            secondary: '#15803d',
            cardName: '#15803d',
            boyBg: '#dcfce7',
            boyText: '#166534',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🍀',
            pass: '🌧️',
            boy: '🎻',
            girl: '🎭'
        },
        names: [
            // Boy names (25)
            { name: "Liam", gender: "boy" },
            { name: "Aiden", gender: "boy" },
            { name: "Sean", gender: "boy" },
            { name: "Connor", gender: "boy" },
            { name: "Finn", gender: "boy" },
            { name: "Patrick", gender: "boy" },
            { name: "Ryan", gender: "boy" },
            { name: "Ronan", gender: "boy" },
            { name: "Declan", gender: "boy" },
            { name: "Cillian", gender: "boy" },
            { name: "Eamon", gender: "boy" },
            { name: "Kieran", gender: "boy" },
            { name: "Brendan", gender: "boy" },
            { name: "Colin", gender: "boy" },
            { name: "Donal", gender: "boy" },
            { name: "Oisin", gender: "boy" },
            { name: "Fergus", gender: "boy" },
            { name: "Cormac", gender: "boy" },
            { name: "Niall", gender: "boy" },
            { name: "Eoghan", gender: "boy" },
            { name: "Tadhg", gender: "boy" },
            { name: "Ciaran", gender: "boy" },
            { name: "Seamus", gender: "boy" },
            { name: "Lorcan", gender: "boy" },
            { name: "Donovan", gender: "boy" },
            
            // Girl names (25)
            { name: "Saoirse", gender: "girl" },
            { name: "Niamh", gender: "girl" },
            { name: "Aoife", gender: "girl" },
            { name: "Siobhan", gender: "girl" },
            { name: "Fiona", gender: "girl" },
            { name: "Maeve", gender: "girl" },
            { name: "Aisling", gender: "girl" },
            { name: "Ciara", gender: "girl" },
            { name: "Roisin", gender: "girl" },
            { name: "Deirdre", gender: "girl" },
            { name: "Orla", gender: "girl" },
            { name: "Sinead", gender: "girl" },
            { name: "Bridget", gender: "girl" },
            { name: "Maureen", gender: "girl" },
            { name: "Kathleen", gender: "girl" },
            { name: "Eileen", gender: "girl" },
            { name: "Moira", gender: "girl" },
            { name: "Grania", gender: "girl" },
            { name: "Cara", gender: "girl" },
            { name: "Brenna", gender: "girl" },
            { name: "Clodagh", gender: "girl" },
            { name: "Caoimhe", gender: "girl" },
            { name: "Eabha", gender: "girl" },
            { name: "Ailbhe", gender: "girl" },
            { name: "Eithne", gender: "girl" }
        ]
    },
    
    russian: {
        id: 'russian',
        name: '🪆 Russian',
        description: 'Slavic traditional names',
        colors: {
            primary: '#dc2626',
            secondary: '#991b1b',
            cardName: '#b91c1c',
            boyBg: '#fee2e2',
            boyText: '#991b1b',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '⭐',
            pass: '❄️',
            boy: '🎻',
            girl: '🌺'
        },
        names: [
            // Boy names (25)
            { name: "Aleksandr", gender: "boy" },
            { name: "Dmitri", gender: "boy" },
            { name: "Ivan", gender: "boy" },
            { name: "Mikhail", gender: "boy" },
            { name: "Nikolai", gender: "boy" },
            { name: "Vladimir", gender: "boy" },
            { name: "Alexei", gender: "boy" },
            { name: "Sergei", gender: "boy" },
            { name: "Andrei", gender: "boy" },
            { name: "Pavel", gender: "boy" },
            { name: "Yuri", gender: "boy" },
            { name: "Boris", gender: "boy" },
            { name: "Viktor", gender: "boy" },
            { name: "Maxim", gender: "boy" },
            { name: "Roman", gender: "boy" },
            { name: "Anatoly", gender: "boy" },
            { name: "Grigori", gender: "boy" },
            { name: "Ilya", gender: "boy" },
            { name: "Stanislav", gender: "boy" },
            { name: "Vasily", gender: "boy" },
            { name: "Konstantin", gender: "boy" },
            { name: "Oleg", gender: "boy" },
            { name: "Ruslan", gender: "boy" },
            { name: "Timur", gender: "boy" },
            { name: "Artem", gender: "boy" },
            
            // Girl names (25)
            { name: "Anastasia", gender: "girl" },
            { name: "Ekaterina", gender: "girl" },
            { name: "Natasha", gender: "girl" },
            { name: "Svetlana", gender: "girl" },
            { name: "Tatiana", gender: "girl" },
            { name: "Irina", gender: "girl" },
            { name: "Marina", gender: "girl" },
            { name: "Olga", gender: "girl" },
            { name: "Yelena", gender: "girl" },
            { name: "Yulia", gender: "girl" },
            { name: "Darya", gender: "girl" },
            { name: "Ksenia", gender: "girl" },
            { name: "Valentina", gender: "girl" },
            { name: "Galina", gender: "girl" },
            { name: "Nadezhda", gender: "girl" },
            { name: "Lyudmila", gender: "girl" },
            { name: "Vera", gender: "girl" },
            { name: "Polina", gender: "girl" },
            { name: "Sofia", gender: "girl" },
            { name: "Alina", gender: "girl" },
            { name: "Varvara", gender: "girl" },
            { name: "Milana", gender: "girl" },
            { name: "Kira", gender: "girl" },
            { name: "Arina", gender: "girl" },
            { name: "Daria", gender: "girl" }
        ]
    },
    
    african: {
        id: 'african',
        name: '🌍 African',
        description: 'Pan-African heritage',
        colors: {
            primary: '#ea580c',
            secondary: '#c2410c',
            cardName: '#c2410c',
            boyBg: '#ffedd5',
            boyText: '#9a3412',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🦁',
            pass: '🌙',
            boy: '🥁',
            girl: '👑'
        },
        names: [
            // Boy names (25)
            { name: "Kwame", gender: "boy" },
            { name: "Kofi", gender: "boy" },
            { name: "Jabari", gender: "boy" },
            { name: "Amari", gender: "boy" },
            { name: "Zaire", gender: "boy" },
            { name: "Malik", gender: "boy" },
            { name: "Omari", gender: "boy" },
            { name: "Thabo", gender: "boy" },
            { name: "Jomo", gender: "boy" },
            { name: "Kwesi", gender: "boy" },
            { name: "Nkrumah", gender: "boy" },
            { name: "Sekou", gender: "boy" },
            { name: "Adisa", gender: "boy" },
            { name: "Chike", gender: "boy" },
            { name: "Dayo", gender: "boy" },
            { name: "Folami", gender: "boy" },
            { name: "Idris", gender: "boy" },
            { name: "Jelani", gender: "boy" },
            { name: "Kojo", gender: "boy" },
            { name: "Mandela", gender: "boy" },
            { name: "Nnamdi", gender: "boy" },
            { name: "Obioma", gender: "boy" },
            { name: "Sanaa", gender: "boy" },
            { name: "Tafari", gender: "boy" },
            { name: "Zuberi", gender: "boy" },
            
            // Girl names (25)
            { name: "Amara", gender: "girl" },
            { name: "Nia", gender: "girl" },
            { name: "Zuri", gender: "girl" },
            { name: "Ayana", gender: "girl" },
            { name: "Asha", gender: "girl" },
            { name: "Imani", gender: "girl" },
            { name: "Kiana", gender: "girl" },
            { name: "Makena", gender: "girl" },
            { name: "Nala", gender: "girl" },
            { name: "Sanaa", gender: "girl" },
            { name: "Zola", gender: "girl" },
            { name: "Amina", gender: "girl" },
            { name: "Fatoumata", gender: "girl" },
            { name: "Kendi", gender: "girl" },
            { name: "Lethabo", gender: "girl" },
            { name: "Mariam", gender: "girl" },
            { name: "Naledi", gender: "girl" },
            { name: "Ola", gender: "girl" },
            { name: "Safiya", gender: "girl" },
            { name: "Thandiwe", gender: "girl" },
            { name: "Yara", gender: "girl" },
            { name: "Ayo", gender: "girl" },
            { name: "Chiamaka", gender: "girl" },
            { name: "Dalila", gender: "girl" },
            { name: "Eshe", gender: "girl" }
        ]
    },
    
    nordic: {
        id: 'nordic',
        name: '⚡ Nordic',
        description: 'Norse and Scandinavian',
        colors: {
            primary: '#0369a1',
            secondary: '#0c4a6e',
            cardName: '#075985',
            boyBg: '#e0f2fe',
            boyText: '#0c4a6e',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '⚔️',
            pass: '🌊',
            boy: '🛡️',
            girl: '👸'
        },
        names: [
            // Boy names (25)
            { name: "Thor", gender: "boy" },
            { name: "Odin", gender: "boy" },
            { name: "Erik", gender: "boy" },
            { name: "Magnus", gender: "boy" },
            { name: "Lars", gender: "boy" },
            { name: "Soren", gender: "boy" },
            { name: "Bjorn", gender: "boy" },
            { name: "Leif", gender: "boy" },
            { name: "Ragnar", gender: "boy" },
            { name: "Gunnar", gender: "boy" },
            { name: "Ivar", gender: "boy" },
            { name: "Sven", gender: "boy" },
            { name: "Axel", gender: "boy" },
            { name: "Olaf", gender: "boy" },
            { name: "Harald", gender: "boy" },
            { name: "Knut", gender: "boy" },
            { name: "Torsten", gender: "boy" },
            { name: "Njord", gender: "boy" },
            { name: "Vidar", gender: "boy" },
            { name: "Rune", gender: "boy" },
            { name: "Einar", gender: "boy" },
            { name: "Sigurd", gender: "boy" },
            { name: "Halvor", gender: "boy" },
            { name: "Arne", gender: "boy" },
            { name: "Gustav", gender: "boy" },
            
            // Girl names (25)
            { name: "Freya", gender: "girl" },
            { name: "Astrid", gender: "girl" },
            { name: "Ingrid", gender: "girl" },
            { name: "Sigrid", gender: "girl" },
            { name: "Helga", gender: "girl" },
            { name: "Solveig", gender: "girl" },
            { name: "Thora", gender: "girl" },
            { name: "Signe", gender: "girl" },
            { name: "Liv", gender: "girl" },
            { name: "Frida", gender: "girl" },
            { name: "Karin", gender: "girl" },
            { name: "Elin", gender: "girl" },
            { name: "Maja", gender: "girl" },
            { name: "Svea", gender: "girl" },
            { name: "Bodil", gender: "girl" },
            { name: "Greta", gender: "girl" },
            { name: "Hilda", gender: "girl" },
            { name: "Runa", gender: "girl" },
            { name: "Saga", gender: "girl" },
            { name: "Ylva", gender: "girl" },
            { name: "Dagmar", gender: "girl" },
            { name: "Eira", gender: "girl" },
            { name: "Nora", gender: "girl" },
            { name: "Kaja", gender: "girl" },
            { name: "Linnea", gender: "girl" }
        ]
    },
    
    japanese: {
        id: 'japanese',
        name: '🌸 Japanese',
        description: 'Traditional Japanese names',
        colors: {
            primary: '#db2777',
            secondary: '#be185d',
            cardName: '#be185d',
            boyBg: '#fce7f3',
            boyText: '#9f1239',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🎎',
            pass: '🌊',
            boy: '⛩️',
            girl: '🌸'
        },
        names: [
            // Boy names (25)
            { name: "Haruto", gender: "boy" },
            { name: "Yuki", gender: "boy" },
            { name: "Kenji", gender: "boy" },
            { name: "Takeshi", gender: "boy" },
            { name: "Hiroshi", gender: "boy" },
            { name: "Kaito", gender: "boy" },
            { name: "Ryu", gender: "boy" },
            { name: "Satoshi", gender: "boy" },
            { name: "Akira", gender: "boy" },
            { name: "Daiki", gender: "boy" },
            { name: "Hayato", gender: "boy" },
            { name: "Ren", gender: "boy" },
            { name: "Sora", gender: "boy" },
            { name: "Yuto", gender: "boy" },
            { name: "Kenzo", gender: "boy" },
            { name: "Masaru", gender: "boy" },
            { name: "Naoki", gender: "boy" },
            { name: "Shinji", gender: "boy" },
            { name: "Taro", gender: "boy" },
            { name: "Yukio", gender: "boy" },
            { name: "Ichiro", gender: "boy" },
            { name: "Jiro", gender: "boy" },
            { name: "Makoto", gender: "boy" },
            { name: "Ryota", gender: "boy" },
            { name: "Shota", gender: "boy" },
            
            // Girl names (25)
            { name: "Sakura", gender: "girl" },
            { name: "Yui", gender: "girl" },
            { name: "Hana", gender: "girl" },
            { name: "Aiko", gender: "girl" },
            { name: "Mei", gender: "girl" },
            { name: "Rin", gender: "girl" },
            { name: "Akari", gender: "girl" },
            { name: "Yuna", gender: "girl" },
            { name: "Himari", gender: "girl" },
            { name: "Koharu", gender: "girl" },
            { name: "Misaki", gender: "girl" },
            { name: "Nanami", gender: "girl" },
            { name: "Ayaka", gender: "girl" },
            { name: "Haruka", gender: "girl" },
            { name: "Kasumi", gender: "girl" },
            { name: "Miyu", gender: "girl" },
            { name: "Natsuki", gender: "girl" },
            { name: "Reina", gender: "girl" },
            { name: "Shiori", gender: "girl" },
            { name: "Yuka", gender: "girl" },
            { name: "Chihiro", gender: "girl" },
            { name: "Emiko", gender: "girl" },
            { name: "Kaede", gender: "girl" },
            { name: "Midori", gender: "girl" },
            { name: "Tomoko", gender: "girl" }
        ]
    },
    
    italian: {
        id: 'italian',
        name: '🇮🇹 Italian',
        description: 'Classic Italian names',
        colors: {
            primary: '#16a34a',
            secondary: '#15803d',
            cardName: '#15803d',
            boyBg: '#dcfce7',
            boyText: '#166534',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🍝',
            pass: '🍕',
            boy: '🎭',
            girl: '🌹'
        },
        names: [
            // Boy names (25)
            { name: "Leonardo", gender: "boy" },
            { name: "Matteo", gender: "boy" },
            { name: "Alessandro", gender: "boy" },
            { name: "Marco", gender: "boy" },
            { name: "Luca", gender: "boy" },
            { name: "Giovanni", gender: "boy" },
            { name: "Antonio", gender: "boy" },
            { name: "Francesco", gender: "boy" },
            { name: "Lorenzo", gender: "boy" },
            { name: "Riccardo", gender: "boy" },
            { name: "Andrea", gender: "boy" },
            { name: "Gabriele", gender: "boy" },
            { name: "Tommaso", gender: "boy" },
            { name: "Stefano", gender: "boy" },
            { name: "Paolo", gender: "boy" },
            { name: "Vincenzo", gender: "boy" },
            { name: "Roberto", gender: "boy" },
            { name: "Daniele", gender: "boy" },
            { name: "Emanuele", gender: "boy" },
            { name: "Salvatore", gender: "boy" },
            { name: "Giulio", gender: "boy" },
            { name: "Carlo", gender: "boy" },
            { name: "Filippo", gender: "boy" },
            { name: "Angelo", gender: "boy" },
            { name: "Dario", gender: "boy" },
            
            // Girl names (25)
            { name: "Giulia", gender: "girl" },
            { name: "Sofia", gender: "girl" },
            { name: "Aurora", gender: "girl" },
            { name: "Chiara", gender: "girl" },
            { name: "Francesca", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Valentina", gender: "girl" },
            { name: "Alessia", gender: "girl" },
            { name: "Martina", gender: "girl" },
            { name: "Giorgia", gender: "girl" },
            { name: "Elisa", gender: "girl" },
            { name: "Sara", gender: "girl" },
            { name: "Elena", gender: "girl" },
            { name: "Beatrice", gender: "girl" },
            { name: "Camilla", gender: "girl" },
            { name: "Arianna", gender: "girl" },
            { name: "Greta", gender: "girl" },
            { name: "Bianca", gender: "girl" },
            { name: "Serena", gender: "girl" },
            { name: "Vittoria", gender: "girl" },
            { name: "Carlotta", gender: "girl" },
            { name: "Margherita", gender: "girl" },
            { name: "Angelica", gender: "girl" },
            { name: "Claudia", gender: "girl" },
            { name: "Federica", gender: "girl" }
        ]
    },
    
    spanish: {
        id: 'spanish',
        name: '💃 Spanish',
        description: 'Spanish and Latin names',
        colors: {
            primary: '#dc2626',
            secondary: '#991b1b',
            cardName: '#b91c1c',
            boyBg: '#fee2e2',
            boyText: '#991b1b',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🌹',
            pass: '🌙',
            boy: '🎸',
            girl: '💃'
        },
        names: [
            // Boy names (25)
            { name: "Mateo", gender: "boy" },
            { name: "Santiago", gender: "boy" },
            { name: "Sebastian", gender: "boy" },
            { name: "Alejandro", gender: "boy" },
            { name: "Diego", gender: "boy" },
            { name: "Carlos", gender: "boy" },
            { name: "Miguel", gender: "boy" },
            { name: "Rafael", gender: "boy" },
            { name: "Javier", gender: "boy" },
            { name: "Fernando", gender: "boy" },
            { name: "Eduardo", gender: "boy" },
            { name: "Luis", gender: "boy" },
            { name: "Pablo", gender: "boy" },
            { name: "Manuel", gender: "boy" },
            { name: "Ricardo", gender: "boy" },
            { name: "Andres", gender: "boy" },
            { name: "Emilio", gender: "boy" },
            { name: "Marcos", gender: "boy" },
            { name: "Antonio", gender: "boy" },
            { name: "Gabriel", gender: "boy" },
            { name: "Rodrigo", gender: "boy" },
            { name: "Joaquin", gender: "boy" },
            { name: "Adrian", gender: "boy" },
            { name: "Raul", gender: "boy" },
            { name: "Oscar", gender: "boy" },
            
            // Girl names (25)
            { name: "Sofia", gender: "girl" },
            { name: "Isabella", gender: "girl" },
            { name: "Valentina", gender: "girl" },
            { name: "Camila", gender: "girl" },
            { name: "Maria", gender: "girl" },
            { name: "Lucia", gender: "girl" },
            { name: "Elena", gender: "girl" },
            { name: "Carmen", gender: "girl" },
            { name: "Rosa", gender: "girl" },
            { name: "Ana", gender: "girl" },
            { name: "Gabriela", gender: "girl" },
            { name: "Adriana", gender: "girl" },
            { name: "Catalina", gender: "girl" },
            { name: "Daniela", gender: "girl" },
            { name: "Natalia", gender: "girl" },
            { name: "Paula", gender: "girl" },
            { name: "Laura", gender: "girl" },
            { name: "Marina", gender: "girl" },
            { name: "Veronica", gender: "girl" },
            { name: "Silvia", gender: "girl" },
            { name: "Teresa", gender: "girl" },
            { name: "Beatriz", gender: "girl" },
            { name: "Pilar", gender: "girl" },
            { name: "Rocio", gender: "girl" },
            { name: "Alejandra", gender: "girl" }
        ]
    },
    
    greek: {
        id: 'greek',
        name: '🏛️ Greek',
        description: 'Ancient Greek heritage',
        colors: {
            primary: '#2563eb',
            secondary: '#1d4ed8',
            cardName: '#1e40af',
            boyBg: '#dbeafe',
            boyText: '#1e40af',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🏛️',
            pass: '🌊',
            boy: '⚡',
            girl: '🦋'
        },
        names: [
            // Boy names (25)
            { name: "Alexander", gender: "boy" },
            { name: "Dimitri", gender: "boy" },
            { name: "Andreas", gender: "boy" },
            { name: "Nikolaos", gender: "boy" },
            { name: "Georgios", gender: "boy" },
            { name: "Constantine", gender: "boy" },
            { name: "Stavros", gender: "boy" },
            { name: "Christos", gender: "boy" },
            { name: "Theodoros", gender: "boy" },
            { name: "Leonidas", gender: "boy" },
            { name: "Panagiotis", gender: "boy" },
            { name: "Kostas", gender: "boy" },
            { name: "Yiannis", gender: "boy" },
            { name: "Petros", gender: "boy" },
            { name: "Apollo", gender: "boy" },
            { name: "Atlas", gender: "boy" },
            { name: "Orion", gender: "boy" },
            { name: "Perseus", gender: "boy" },
            { name: "Achilles", gender: "boy" },
            { name: "Odysseus", gender: "boy" },
            { name: "Theseus", gender: "boy" },
            { name: "Paris", gender: "boy" },
            { name: "Hector", gender: "boy" },
            { name: "Jason", gender: "boy" },
            { name: "Damon", gender: "boy" },
            
            // Girl names (25)
            { name: "Athena", gender: "girl" },
            { name: "Sophia", gender: "girl" },
            { name: "Helena", gender: "girl" },
            { name: "Maria", gender: "girl" },
            { name: "Eleni", gender: "girl" },
            { name: "Katerina", gender: "girl" },
            { name: "Anastasia", gender: "girl" },
            { name: "Daphne", gender: "girl" },
            { name: "Calliope", gender: "girl" },
            { name: "Persephone", gender: "girl" },
            { name: "Penelope", gender: "girl" },
            { name: "Chloe", gender: "girl" },
            { name: "Zoe", gender: "girl" },
            { name: "Iris", gender: "girl" },
            { name: "Thalia", gender: "girl" },
            { name: "Ioanna", gender: "girl" },
            { name: "Dimitra", gender: "girl" },
            { name: "Vasiliki", gender: "girl" },
            { name: "Fotini", gender: "girl" },
            { name: "Evangelia", gender: "girl" },
            { name: "Antigone", gender: "girl" },
            { name: "Cassandra", gender: "girl" },
            { name: "Elektra", gender: "girl" },
            { name: "Xanthe", gender: "girl" },
            { name: "Ianthe", gender: "girl" }
        ]
    },
    
    arabic: {
        id: 'arabic',
        name: '🌙 Arabic',
        description: 'Middle Eastern names',
        colors: {
            primary: '#7c2d12',
            secondary: '#92400e',
            cardName: '#92400e',
            boyBg: '#fed7aa',
            boyText: '#7c2d12',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '⭐',
            pass: '🌙',
            boy: '🕌',
            girl: '🌹'
        },
        names: [
            // Boy names (25)
            { name: "Omar", gender: "boy" },
            { name: "Ali", gender: "boy" },
            { name: "Hassan", gender: "boy" },
            { name: "Ibrahim", gender: "boy" },
            { name: "Khalid", gender: "boy" },
            { name: "Youssef", gender: "boy" },
            { name: "Ahmed", gender: "boy" },
            { name: "Amir", gender: "boy" },
            { name: "Karim", gender: "boy" },
            { name: "Tariq", gender: "boy" },
            { name: "Rashid", gender: "boy" },
            { name: "Samir", gender: "boy" },
            { name: "Malik", gender: "boy" },
            { name: "Zain", gender: "boy" },
            { name: "Rayan", gender: "boy" },
            { name: "Faisal", gender: "boy" },
            { name: "Jamal", gender: "boy" },
            { name: "Nasir", gender: "boy" },
            { name: "Salim", gender: "boy" },
            { name: "Aziz", gender: "boy" },
            { name: "Fahad", gender: "boy" },
            { name: "Hamza", gender: "boy" },
            { name: "Idris", gender: "boy" },
            { name: "Mehdi", gender: "boy" },
            { name: "Nabil", gender: "boy" },
            
            // Girl names (25)
            { name: "Aisha", gender: "girl" },
            { name: "Fatima", gender: "girl" },
            { name: "Layla", gender: "girl" },
            { name: "Amira", gender: "girl" },
            { name: "Yasmin", gender: "girl" },
            { name: "Zara", gender: "girl" },
            { name: "Noor", gender: "girl" },
            { name: "Amina", gender: "girl" },
            { name: "Samira", gender: "girl" },
            { name: "Zahra", gender: "girl" },
            { name: "Mariam", gender: "girl" },
            { name: "Leila", gender: "girl" },
            { name: "Rania", gender: "girl" },
            { name: "Soraya", gender: "girl" },
            { name: "Salma", gender: "girl" },
            { name: "Hana", gender: "girl" },
            { name: "Jamila", gender: "girl" },
            { name: "Nadine", gender: "girl" },
            { name: "Rasha", gender: "girl" },
            { name: "Safiya", gender: "girl" },
            { name: "Dalia", gender: "girl" },
            { name: "Farah", gender: "girl" },
            { name: "Karima", gender: "girl" },
            { name: "Lina", gender: "girl" },
            { name: "Maya", gender: "girl" }
        ]
    },
    
    indian: {
        id: 'indian',
        name: '🪷 Indian',
        description: 'Traditional Indian names',
        colors: {
            primary: '#ea580c',
            secondary: '#c2410c',
            cardName: '#c2410c',
            boyBg: '#ffedd5',
            boyText: '#9a3412',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '🪷',
            pass: '🌙',
            boy: '🕉️',
            girl: '💐'
        },
        names: [
            // Boy names (25)
            { name: "Arjun", gender: "boy" },
            { name: "Aarav", gender: "boy" },
            { name: "Rohan", gender: "boy" },
            { name: "Aditya", gender: "boy" },
            { name: "Aryan", gender: "boy" },
            { name: "Dev", gender: "boy" },
            { name: "Karan", gender: "boy" },
            { name: "Ravi", gender: "boy" },
            { name: "Vikram", gender: "boy" },
            { name: "Raj", gender: "boy" },
            { name: "Nikhil", gender: "boy" },
            { name: "Pranav", gender: "boy" },
            { name: "Sanjay", gender: "boy" },
            { name: "Vivek", gender: "boy" },
            { name: "Krishna", gender: "boy" },
            { name: "Rahul", gender: "boy" },
            { name: "Amit", gender: "boy" },
            { name: "Anish", gender: "boy" },
            { name: "Deepak", gender: "boy" },
            { name: "Harish", gender: "boy" },
            { name: "Akash", gender: "boy" },
            { name: "Gaurav", gender: "boy" },
            { name: "Manoj", gender: "boy" },
            { name: "Suresh", gender: "boy" },
            { name: "Varun", gender: "boy" },
            
            // Girl names (25)
            { name: "Priya", gender: "girl" },
            { name: "Ananya", gender: "girl" },
            { name: "Aadhya", gender: "girl" },
            { name: "Diya", gender: "girl" },
            { name: "Saanvi", gender: "girl" },
            { name: "Anika", gender: "girl" },
            { name: "Kavya", gender: "girl" },
            { name: "Meera", gender: "girl" },
            { name: "Neha", gender: "girl" },
            { name: "Pooja", gender: "girl" },
            { name: "Riya", gender: "girl" },
            { name: "Siya", gender: "girl" },
            { name: "Tara", gender: "girl" },
            { name: "Uma", gender: "girl" },
            { name: "Lakshmi", gender: "girl" },
            { name: "Maya", gender: "girl" },
            { name: "Nisha", gender: "girl" },
            { name: "Anjali", gender: "girl" },
            { name: "Divya", gender: "girl" },
            { name: "Shriya", gender: "girl" },
            { name: "Isha", gender: "girl" },
            { name: "Kritika", gender: "girl" },
            { name: "Mansi", gender: "girl" },
            { name: "Simran", gender: "girl" },
            { name: "Zara", gender: "girl" }
        ]
    },
    
    french: {
        id: 'french',
        name: '🗼 French',
        description: 'Classic French names',
        colors: {
            primary: '#2563eb',
            secondary: '#1d4ed8',
            cardName: '#1e40af',
            boyBg: '#dbeafe',
            boyText: '#1e40af',
            girlBg: '#fef3c7',
            girlText: '#92400e'
        },
        icons: {
            like: '💖',
            pass: '🥐',
            boy: '🎭',
            girl: '🌹'
        },
        names: [
            // Boy names (25)
            { name: "Louis", gender: "boy" },
            { name: "Gabriel", gender: "boy" },
            { name: "Raphael", gender: "boy" },
            { name: "Jules", gender: "boy" },
            { name: "Lucas", gender: "boy" },
            { name: "Hugo", gender: "boy" },
            { name: "Antoine", gender: "boy" },
            { name: "Pierre", gender: "boy" },
            { name: "Alexandre", gender: "boy" },
            { name: "Olivier", gender: "boy" },
            { name: "Etienne", gender: "boy" },
            { name: "Sebastien", gender: "boy" },
            { name: "Thierry", gender: "boy" },
            { name: "Laurent", gender: "boy" },
            { name: "Fabien", gender: "boy" },
            { name: "Maxime", gender: "boy" },
            { name: "Nicolas", gender: "boy" },
            { name: "Romain", gender: "boy" },
            { name: "Vincent", gender: "boy" },
            { name: "Marc", gender: "boy" },
            { name: "Pascal", gender: "boy" },
            { name: "Valentin", gender: "boy" },
            { name: "Mathieu", gender: "boy" },
            { name: "Julien", gender: "boy" },
            { name: "Benoit", gender: "boy" },
            
            // Girl names (25)
            { name: "Emma", gender: "girl" },
            { name: "Louise", gender: "girl" },
            { name: "Chloe", gender: "girl" },
            { name: "Camille", gender: "girl" },
            { name: "Sophie", gender: "girl" },
            { name: "Charlotte", gender: "girl" },
            { name: "Amelie", gender: "girl" },
            { name: "Claire", gender: "girl" },
            { name: "Margaux", gender: "girl" },
            { name: "Juliette", gender: "girl" },
            { name: "Lea", gender: "girl" },
            { name: "Manon", gender: "girl" },
            { name: "Marie", gender: "girl" },
            { name: "Oceane", gender: "girl" },
            { name: "Pauline", gender: "girl" },
            { name: "Elise", gender: "girl" },
            { name: "Lucie", gender: "girl" },
            { name: "Anais", gender: "girl" },
            { name: "Aurelie", gender: "girl" },
            { name: "Celine", gender: "girl" },
            { name: "Delphine", gender: "girl" },
            { name: "Emilie", gender: "girl" },
            { name: "Isabelle", gender: "girl" },
            { name: "Nathalie", gender: "girl" },
            { name: "Sylvie", gender: "girl" }
        ]
    }
};
